### ISSUE TITLE
Drag & Drop ish

### ISSUE THREAD

**Issue by kit-matthewson** [Jackaed/Antichess#1]
![bitmoji](https://sdk.bitmoji.com/render/panel/5fa47f43-878b-4b22-91b8-6f897c1c7cd4-5c27b019-70a8-4bb5-ab46-7b5938de1593-v1.png?transparent=1&palette=1&width=246)

remove drag & drop

**Comment by Jackaed** [comment]
Make your way over to cliffton suspension bridge.
